FROM ubuntu:22.04

ARG USER=hp

RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get -y install sudo \
    bridge-utils iproute2 iputils-ping net-tools \
    bash-completion curl expect httpie jq vim wget \
    build-essential clang flex bison g++ gawk \
    gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
    python3-distutils rsync unzip zlib1g-dev file wget

RUN useradd --create-home ${USER} && usermod -aG sudo ${USER} \
    && echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USER} \
    && chmod 0440 /etc/sudoers.d/${USER}
USER ${USER}
ENV HOME=/home/${USER}
WORKDIR $HOME
ENV PATH="$HOME/.local/bin:$HOME/bin:$PATH"

